[package]
name = "nordvpn_tray_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ksni = "0.2.1"
regex = "1.10.5"
syslog = "7.0.0"
